name: evimoon
description: Private by Design cycle tracker. # Исправил описание на более профессиональное
publish_to: 'none'
version: 1.0.2+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # База и Утилиты
  intl: ^0.20.2
  provider: ^6.1.1
  google_fonts: ^6.1.0
  timezone: ^0.9.2

  # Локальное хранение (Hive + Secure Storage)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Функционал
  local_auth: ^2.1.6        # Биометрия
  table_calendar: ^3.1.0
  flutter_local_notifications: ^17.0.0

  # PDF и Файлы
  pdf: ^3.10.4
  printing: ^5.11.0
  share_plus: ^10.0.0       # Для отправки бэкапа
  file_picker: ^8.0.0       # Для загрузки бэкапа
  path_provider: ^2.1.2
  url_launcher: ^6.2.0      # Для кнопки поддержки

  # UI
  fl_chart: ^0.66.0
  animated_flip_counter: ^0.2.5
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  purchases_flutter: ^9.10.6
  collection: ^1.18.0
  flutter_timezone: ^2.0.0
  cryptography: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Генерация кода (Здесь им самое место)
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

  # Иконки и сплэш
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  analyzer: ^5.13.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/icon/

  fonts:
    - family: Didot
      fonts:
        - asset: assets/fonts/GFSDidot-Regular.ttf

# Конфигурация иконки
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  # Если есть адаптивная иконка для Android, раскомментируй и проверь пути:
  # adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_foreground: "assets/icon/icon.png"